// The Gradle plugin(s) (D1/D10): `net.sarazan.articulate` (source discovery,
// generateAndroidRes/generateXcstrings/generateStrings/verifyStrings, the
// extension) and `net.sarazan.articulate.android` (AGP variant res wiring
// only). Thin — delegates all real logic to `core`.
//
// AGP is `compileOnly` and pinned to the D9 floor (8.5.2) precisely so this
// module cannot accidentally compile against a newer AGP API that a
// floor-Gradle/floor-AGP consumer's runtime wouldn't have — see
// GradleFloorFunctionalTest, which exercises the actual floor via TestKit.
import org.gradle.plugin.devel.tasks.PluginUnderTestMetadata

plugins {
    alias(libs.plugins.kotlin.jvm)
    `java-gradle-plugin`
    alias(libs.plugins.plugin.publish)
}

// Publishing coordinates. 0.1.0 deliberately, not 1.0.0: `markupPolicy` accepts
// values whose implementations are deferred (D4) and the isolated-projects
// incompatibility (PLAN.md §13) is a tracked redesign. 0.x is the honest signal.
// Set per-module rather than via allprojects{} -- the root script forbids
// cross-project configuration precisely because it breaks project isolation.
group = "net.sarazan.articulate"
version = "0.1.0"

// The Gradle module directory is `plugin/`, which would otherwise leak into
// permanent public coordinates as `net.sarazan.articulate:plugin`. Two separate
// knobs are needed: `archivesName` renames the built file, while maven-publish
// derives the published artifactId from the project name independently.
base.archivesName.set("articulate-gradle-plugin")

publishing {
    publications {
        // Only the implementation publication. The two `*.gradle.plugin` marker
        // publications are generated by plugin-publish and their coordinates are
        // fixed by Gradle convention (groupId = the plugin id) -- renaming those
        // would break `plugins { id("net.sarazan.articulate") }` resolution.
        withType<MavenPublication>().configureEach {
            if (name == "pluginMaven") {
                artifactId = "articulate-gradle-plugin"
            }
        }
    }
}

kotlin {
    // Pins the compile JDK independently of whatever JDK launches Gradle —
    // matches AGP 8.x's own JDK 17 requirement (PLAN.md §12).
    jvmToolchain(17)
}

// AGP added here, not as a `dependencies {}` scope, precisely so it is never
// part of `compileClasspath`/`runtimeClasspath`/anything that flows into the
// published POM of either plugin ID -- D10's whole point is that a
// non-Android consumer of `net.sarazan.articulate` never pulls AGP onto its
// classpath, and the two plugin IDs share this one jar. This configuration
// exists purely to feed `pluginUnderTestMetadata` below, for TestKit.
val agpTestKitClasspath: Configuration by configurations.creating {
    isCanBeConsumed = false
}

// Task 3 / D9's upper matrix cell (PLAN.md §E2): AGP 9.1, never previously
// exercised anywhere. Deliberately a *separate* configuration from
// agpTestKitClasspath above, not an additional dependency on it -- putting
// both AGP 8.5.2 and 9.1.0 on the same classpath would load conflicting
// copies of the same classes with an arbitrary winner. AndroidWiringAgp91FunctionalTest
// builds its own explicit TestKit plugin classpath from this at runtime
// (see agp91PluginUnderTestMetadata below) instead of using the default,
// classpath-resource-based GradleRunner.withPluginClasspath() that every
// other functional test relies on -- that default is permanently pinned to
// AGP 8.5.2 via agpTestKitClasspath/pluginUnderTestMetadata, the floor cell.
val agp91TestKitClasspath: Configuration by configurations.creating {
    isCanBeConsumed = false
}

// `core` is BUNDLED into this jar rather than published as its own artifact.
// The core/plugin *module* split (D1) exists for development -- fast unit tests
// with no Gradle API on core's classpath -- and survives bundling untouched.
// Publishing core separately was never actually decided; it fell out of Gradle's
// defaults. It would commit us to a public API for a module that is
// `internal`-heavy by design, in service of a standalone-CLI use case nobody
// has asked for. Reversible later: publish core and drop the bundling, which is
// transparent to plugin consumers since Gradle resolves the new transitive dep.
//
// No relocation needed -- this is our own code in a package nobody else could
// own, with no third-party dependencies. Plain bundling, not true shading.
//
// Resolved as a *dependency* rather than reaching into project(":core")'s task
// container, deliberately: cross-project access at configuration time is the
// isolated-projects hazard already tracked in PLAN.md §13, and bundling should
// not deepen that hole.
val bundledCore: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
    isTransitive = false
}

dependencies {
    // compileOnly, not implementation: `implementation` would put
    // net.sarazan.articulate:core into the published POM as a runtime
    // dependency that no repository serves. The classes ship inside this jar
    // instead -- see `bundledCore`.
    compileOnly(project(":core"))
    bundledCore(project(":core"))
    compileOnly(libs.android.gradle.plugin)

    testImplementation(project(":core"))
    testImplementation(gradleTestKit())
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)

    agpTestKitClasspath(libs.android.gradle.plugin)
    // Pinned literally, not via the version catalog: libs.versions.toml's
    // `agp` is D9's floor (8.5.2, compileOnly-pinned so `plugin` can't
    // accidentally compile against a newer API) -- this is the *other*
    // matrix cell, used only for the TestKit fixture classpath below, never
    // for compilation.
    agp91TestKitClasspath("com.android.tools.build:gradle:9.1.0")
}

gradlePlugin {
    // Portal metadata (D11: Plugin Portal first). `website`/`vcsUrl` are
    // required by com.gradle.plugin-publish; publishing fails without them.
    website.set("https://github.com/asarazan/articulate")
    vcsUrl.set("https://github.com/asarazan/articulate")

    plugins {
        create("articulate") {
            id = "net.sarazan.articulate"
            implementationClass = "net.sarazan.articulate.gradle.ArticulatePlugin"
            displayName = "Articulate"
            description = "Generates an Xcode String Catalog from Android strings.xml, and verifies it hasn't drifted."
            tags.set(listOf("android", "ios", "kotlin-multiplatform", "localization", "i18n", "xcstrings"))
        }
        create("articulateAndroid") {
            id = "net.sarazan.articulate.android"
            implementationClass = "net.sarazan.articulate.gradle.ArticulateAndroidPlugin"
            displayName = "Articulate (Android variant wiring)"
            description = "Wires Articulate's generated Android resources into AGP variant sources."
            tags.set(listOf("android", "localization", "i18n", "agp"))
        }
    }
    // Explicit rather than relying on java-gradle-plugin's default source-set
    // detection: wires this module's own compiled classes + runtime
    // classpath into `plugin-under-test-metadata.properties`, which
    // GradleRunner.withPluginClasspath() reads to make `plugins { id(...) }`
    // resolvable inside a TestKit fixture project without publishing anything.
    testSourceSets(sourceSets["test"])
}

// `PluginUnderTestMetadata.pluginClasspath` defaults to `sourceSets.main.runtimeClasspath`
// alone, which never includes `compileOnly(libs.android.gradle.plugin)` --
// `compileOnly` is deliberately excluded from every runtime classpath by
// Gradle. Without this, ArticulateAndroidPlugin's compiled reference to
// AGP's `ApplicationAndroidComponentsExtension` throws `NoClassDefFoundError`
// inside any TestKit fixture built with `withPluginClasspath()`, since AGP's
// classes are simply absent from the injected classpath -- not merely in a
// different classloader. `.from()` on a `ConfigurableFileCollection` appends
// rather than replaces, so this adds `agpTestKitClasspath` (AGP + its
// transitive deps) alongside the existing default, without touching what
// gets published (see `agpTestKitClasspath`'s own comment, above).
// Unpack core's classes into this jar. `zipTree` inside a provider keeps it
// lazy; `bundledCore` is non-transitive so only core itself is unpacked, never
// the Kotlin stdlib (which Gradle supplies to plugins anyway).
tasks.jar {
    from(provider { bundledCore.resolve().map { zipTree(it) } })
}

// `pluginUnderTestMetadata` builds the classpath TestKit fixtures resolve
// `plugins { id(...) }` against, and defaults to `sourceSets.main.runtimeClasspath`
// -- which no longer contains core now that it is `compileOnly`. Add both core
// and AGP explicitly, or every functional test fails with NoClassDefFoundError.
tasks.named<PluginUnderTestMetadata>("pluginUnderTestMetadata") {
    pluginClasspath.from(agpTestKitClasspath, bundledCore)
}

// Task 3's AGP 9.1 cell: a second, independent PluginUnderTestMetadata task
// (own name, own output directory) so its properties file never collides
// with the default `pluginUnderTestMetadata` above on any classpath --
// AndroidWiringAgp91FunctionalTest reads this one's output file directly by
// path (via the system property wired into `tasks.test` below) rather than
// relying on classpath-resource lookup, precisely so both metadata files can
// coexist in the same `test` source set without one shadowing the other.
val agp91PluginUnderTestMetadata = tasks.register<PluginUnderTestMetadata>("agp91PluginUnderTestMetadata") {
    pluginClasspath.from(sourceSets["main"].runtimeClasspath, bundledCore, agp91TestKitClasspath)
    outputDirectory.set(layout.buildDirectory.dir("agp91PluginUnderTestMetadata"))
}

tasks.test {
    useJUnitPlatform()
    dependsOn(agp91PluginUnderTestMetadata)
    systemProperty(
        "articulate.agp91PluginUnderTestMetadata",
        agp91PluginUnderTestMetadata.get().outputDirectory.file("plugin-under-test-metadata.properties").get().asFile.absolutePath,
    )
}
