// The Gradle plugin(s) (D1/D10): `net.sarazan.articulate` (source discovery,
// validateStrings/generateXcstrings/generateStrings/verifyStrings, the
// extension) and `net.sarazan.articulate.android` (AGP variant res wiring
// only). Thin — delegates all real logic to `core`.
//
// AGP is `compileOnly` and pinned to the D9 floor (9.1.0) precisely so this
// module cannot accidentally compile against a newer AGP API that a
// floor-Gradle/floor-AGP consumer's runtime wouldn't have — see
// GradleFloorFunctionalTest, which exercises the actual floor via TestKit.
import org.gradle.plugin.devel.tasks.PluginUnderTestMetadata

plugins {
    alias(libs.plugins.kotlin.jvm)
    `java-gradle-plugin`
    alias(libs.plugins.plugin.publish)
    // §16.1: additive to plugin-publish's three publications -- uploads them
    // to the Central Portal, does not create its own.
    alias(libs.plugins.nmcp)
    // §16.2: in-memory keys so CI needs no keyring file. Configured below,
    // conditional on credentials being present -- see the trap this guards.
    signing
}

// Publishing coordinates. 0.1.0 deliberately, not 1.0.0: `markupPolicy` accepts
// VERBATIM in the DSL but it is not implemented (D4) -- ERROR and STRIP both
// are -- the M6 Swift key-parity lint is not built, and generated common-layer
// tokens are scoped but not built (PLAN.md §14 amendment). 0.x is the honest signal.
// Set per-module rather than via allprojects{} -- the root script forbids
// cross-project configuration precisely because it breaks project isolation.
group = "net.sarazan.articulate"
version = "0.1.0"

// The Gradle module directory is `plugin/`, which would otherwise leak into
// permanent public coordinates as `net.sarazan.articulate:plugin`. Two separate
// knobs are needed: `archivesName` renames the built file, while maven-publish
// derives the published artifactId from the project name independently.
base.archivesName.set("articulate-gradle-plugin")

// Shared with the `gradlePlugin` block below so the POM and the Portal listing
// cannot drift apart.
val articulateDescription =
    "Generates an Xcode String Catalog from Android strings.xml, and verifies it hasn't drifted."

publishing {
    publications {
        // Only the implementation publication. The two `*.gradle.plugin` marker
        // publications are generated by plugin-publish and their coordinates are
        // fixed by Gradle convention (groupId = the plugin id) -- renaming those
        // would break `plugins { id("net.sarazan.articulate") }` resolution.
        withType<MavenPublication>().configureEach {
            if (name == "pluginMaven") {
                artifactId = "articulate-gradle-plugin"
                pom {
                    name.set("Articulate")
                    description.set(articulateDescription)
                }
            }

            // The Apache-2.0 grant lives in `LICENSE` at the repo root, which
            // puts it in the *source* tree and nowhere else -- nothing copies
            // it into published metadata, so without this block every POM we
            // publish declares no license at all. Verified by inspecting the
            // generated POMs under ~/.m2 before this was added: no <licenses>,
            // no <url>. Published coordinates are immutable, so an omission
            // here is permanent for whatever version ships with it.
            pom {
                url.set("https://github.com/asarazan/articulate")
                licenses {
                    license {
                        name.set("The Apache License, Version 2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                        distribution.set("repo")
                    }
                }
                // Maven Central requires <developers> and <scm> on every
                // published POM; the Portal path (Gradle Plugin Portal) never
                // needed them, so they were absent until §16 (PLAN.md).
                // Verified 2026-08-10 by reading the generated POMs under
                // ~/.m2 -- this was the only metadata gap (§16.0).
                developers {
                    developer {
                        id.set("asarazan")
                        name.set("Aaron Sarazan")
                        email.set("aaron@sarazan.net")
                        url.set("https://github.com/asarazan")
                    }
                }
                scm {
                    connection.set("scm:git:git://github.com/asarazan/articulate.git")
                    developerConnection.set("scm:git:ssh://github.com/asarazan/articulate.git")
                    url.set("https://github.com/asarazan/articulate")
                }
            }
        }
    }
}

// §16.1: nmcp uploads plugin-publish's *existing* publications (pluginMaven +
// both `*.gradle.plugin` markers) to the Central Portal -- it creates no
// publications of its own, so nothing above needed to change. Credentials
// read from Gradle properties, never hardcoded (§16.3: human sets these in
// ~/.gradle/gradle.properties or CI secrets; agents never read or set the
// values). Absent properties resolve to an unset Provider, which only fails
// the build if a Central-Portal-uploading task is actually invoked -- see
// nmcp's own `taskGraph.whenReady` check -- so this block does not disturb
// `publishToMavenLocal` or any other task that doesn't touch the network.
//
// `publishAllPublicationsToCentralPortal` is nmcp 1.6.1's single-project API
// -- deprecated in favor of the `com.gradleup.nmcp.aggregation` plugin, whose
// job is combining publications from *multiple* projects into one deployment.
// This module publishes all three of its own publications in one project, so
// aggregation buys nothing here and would be the architecture change §16.1
// says to avoid reaching for without cause; the deprecated function remains
// nmcp's documented single-project entry point and is exercised by nmcp's
// own test suite.
nmcp {
    @Suppress("DEPRECATION")
    publishAllPublicationsToCentralPortal {
        username.set(providers.gradleProperty("mavenCentralUsername"))
        password.set(providers.gradleProperty("mavenCentralPassword"))
        // USER_MANAGED, not the nmcp default AUTOMATIC: matches this repo's
        // posture on irreversible actions (see release.yml's Portal job) --
        // the deployment is validated and uploaded, but a human still visits
        // the Central Portal UI to press "Publish" once it looks right.
        publishingType.set("USER_MANAGED")
    }
}

// §16.2 -- THE TRAP: signing must never break `publishToMavenLocal` (the dev
// loop; showcase/ and every consumer-compatibility check run through it).
//
// No explicit `sign(publishing.publications)` call here: `com.gradle.plugin-publish`
// has signed its own publications automatically since 1.0.0 the moment the
// `signing` plugin is applied to the project (verified 2026-08-10 --
// `signPluginMavenPublication` / `signArticulatePluginMarkerMavenPublication` /
// `signArticulateAndroidPluginMarkerMavenPublication` all appear in
// `:plugin:tasks --all` from applying `signing` alone, with no `sign(...)`
// call anywhere in this file). Calling `sign()` a second time here would
// duplicate that wiring for no benefit and risks the double-signing failure
// mode tracked upstream at gradle/gradle#21857. This block's only job is
// supplying the signatory: `isRequired` gated on both properties being
// present, and `useInMemoryPgpKeys` called only then, so an unconfigured
// signatory never gets asked to sign anything.
//
// Proven by §16.5 item 7: with these properties unset, plugin-publish's
// Sign tasks report SKIPPED (not required, no signatory) and
// `publishToMavenLocal` succeeds.
val signingKey = providers.gradleProperty("signingInMemoryKey")
val signingKeyPassword = providers.gradleProperty("signingInMemoryKeyPassword")
signing {
    isRequired = signingKey.isPresent && signingKeyPassword.isPresent
    if (signingKey.isPresent && signingKeyPassword.isPresent) {
        useInMemoryPgpKeys(signingKey.get(), signingKeyPassword.get())
    }
}

kotlin {
    // Pins the compile JDK independently of whatever JDK launches Gradle —
    // matches AGP 9.1's own JDK 17 requirement (D9, REVISED 2026-08-03;
    // PLAN.md §12/§E2).
    jvmToolchain(17)
}

// AGP added here, not as a `dependencies {}` scope, precisely so it is never
// part of `compileClasspath`/`runtimeClasspath`/anything that flows into the
// published POM of either plugin ID -- D10's whole point is that a
// non-Android consumer of `net.sarazan.articulate` never pulls AGP onto its
// classpath, and the two plugin IDs share this one jar. This configuration
// exists purely to feed `pluginUnderTestMetadata` below, for TestKit.
//
// There used to be a second, parallel TestKit classpath configuration here
// (PLAN.md §E2/D9, Task 3): the matrix's two cells ran different AGP
// versions (8.5.2 floor vs 9.1.0 upper), so each needed its own plugin
// classpath. REVISED 2026-08-03: the floor moved to AGP 9.1.0, so both
// cells now run the *same* AGP -- the matrix's real axis is Gradle version
// (ANDROID_GRADLE_FLOOR_VERSION vs the wrapper), not AGP. With one AGP
// version, this single configuration (which already resolves to the
// catalog's 9.1.0) serves both cells, and the duplicate classpath machinery
// had no remaining job. Deleted.
val agpTestKitClasspath: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

// `core` is BUNDLED into this jar rather than published as its own artifact.
// The core/plugin *module* split (D1) exists for development -- fast unit tests
// with no Gradle API on core's classpath -- and survives bundling untouched.
// Publishing core separately was never actually decided; it fell out of Gradle's
// defaults. It would commit us to a public API for a module that is
// `internal`-heavy by design, in service of a standalone-CLI use case nobody
// has asked for. Reversible later: publish core and drop the bundling, which is
// transparent to plugin consumers since Gradle resolves the new transitive dep.
//
// No relocation needed -- this is our own code in a package nobody else could
// own, with no third-party dependencies. Plain bundling, not true shading.
//
// Resolved as a *dependency* rather than reaching into project(":core")'s task
// container, deliberately: cross-project access at configuration time is the
// isolated-projects hazard already tracked in PLAN.md §13, and bundling should
// not deepen that hole.
val bundledCore: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
    isTransitive = false
}

dependencies {
    // compileOnly, not implementation: `implementation` would put
    // net.sarazan.articulate:core into the published POM as a runtime
    // dependency that no repository serves. The classes ship inside this jar
    // instead -- see `bundledCore`.
    compileOnly(project(":core"))
    bundledCore(project(":core"))
    compileOnly(libs.android.gradle.plugin)

    testImplementation(project(":core"))
    testImplementation(gradleTestKit())
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)

    agpTestKitClasspath(libs.android.gradle.plugin)
}

gradlePlugin {
    // Portal metadata (D11: Plugin Portal first). `website`/`vcsUrl` are
    // required by com.gradle.plugin-publish; publishing fails without them.
    website.set("https://github.com/asarazan/articulate")
    vcsUrl.set("https://github.com/asarazan/articulate")

    plugins {
        create("articulate") {
            id = "net.sarazan.articulate"
            implementationClass = "net.sarazan.articulate.gradle.ArticulatePlugin"
            displayName = "Articulate"
            description = articulateDescription
            tags.set(listOf("android", "ios", "kotlin-multiplatform", "localization", "i18n", "xcstrings"))
        }
        create("articulateAndroid") {
            id = "net.sarazan.articulate.android"
            implementationClass = "net.sarazan.articulate.gradle.ArticulateAndroidPlugin"
            displayName = "Articulate (Android variant wiring)"
            description = "Wires Articulate's generated Android resources into AGP variant sources."
            tags.set(listOf("android", "localization", "i18n", "agp"))
        }
    }
    // Explicit rather than relying on java-gradle-plugin's default source-set
    // detection: wires this module's own compiled classes + runtime
    // classpath into `plugin-under-test-metadata.properties`, which
    // GradleRunner.withPluginClasspath() reads to make `plugins { id(...) }`
    // resolvable inside a TestKit fixture project without publishing anything.
    testSourceSets(sourceSets["test"])
}

// Unpack core's classes into this jar. `zipTree` inside a provider keeps it
// lazy; `bundledCore` is non-transitive so only core itself is unpacked, never
// the Kotlin stdlib (which Gradle supplies to plugins anyway).
tasks.jar {
    from(provider { bundledCore.resolve().map { zipTree(it) } })
}

// `pluginUnderTestMetadata` builds the classpath TestKit fixtures resolve
// `plugins { id(...) }` against. `PluginUnderTestMetadata.pluginClasspath`
// defaults to `sourceSets.main.runtimeClasspath` alone, which no longer
// contains core (now `compileOnly`) or AGP (`compileOnly(libs.android.gradle.plugin)`
// -- `compileOnly` is deliberately excluded from every runtime classpath by
// Gradle). Without both added explicitly, ArticulateAndroidPlugin's compiled
// reference to AGP's `ApplicationAndroidComponentsExtension` throws
// `NoClassDefFoundError` inside any TestKit fixture built with
// `withPluginClasspath()`, since the needed classes are simply absent from
// the injected classpath -- not merely in a different classloader. `.from()`
// on a `ConfigurableFileCollection` appends rather than replaces, so this adds
// `agpTestKitClasspath` (AGP + its transitive deps) and `bundledCore`
// alongside the existing default, without touching what gets published (see
// `agpTestKitClasspath`'s own comment, above).
tasks.named<PluginUnderTestMetadata>("pluginUnderTestMetadata") {
    pluginClasspath.from(agpTestKitClasspath, bundledCore)
}

tasks.test {
    useJUnitPlatform()
}
