package net.sarazan.articulate.gradle

import org.gradle.testkit.runner.GradleRunner
import java.io.File
import java.nio.file.Path

/**
 * Shared scaffolding for the plugin's TestKit functional tests (PLAN.md §4.8).
 *
 * Fixture build scripts are plain Groovy (`build.gradle`, `settings.gradle`),
 * not Kotlin DSL: `GradleRunner.withPluginClasspath()` injects the
 * plugin-under-test onto the fixture's buildscript classpath at runtime
 * (via `plugin-under-test-metadata.properties`, generated by
 * `plugin/build.gradle.kts`'s `gradlePlugin { testSourceSets(...) }`), and
 * assigning into a Gradle `Property<T>`/`RegularFileProperty` with plain `=`
 * only works through Groovy's built-in decoration for that -- Kotlin DSL
 * needs generated type-safe accessors that don't exist for a plugin applied
 * this way. Groovy is the standard fixture language for exactly this reason.
 */
internal object FunctionalTestSupport {

    /** Minimal settings file: just names the root project. No included builds -- the plugin classpath comes from TestKit injection, not `includeBuild`. */
    fun writeSettings(projectDir: Path, name: String = "fixture") {
        File(projectDir.toFile(), "settings.gradle").writeText(
            "rootProject.name = '$name'\n",
        )
    }

    /**
     * `build.gradle` applying `net.sarazan.articulate` and pointing the
     * committed catalog at `<projectDir>/ios/Shared.xcstrings`, matching the
     * DSL sketch in PLAN.md §E4.
     */
    fun writeBaseBuildFile(projectDir: Path, extraConfig: String = "") {
        File(projectDir.toFile(), "build.gradle").writeText(
            """
            plugins {
                id 'net.sarazan.articulate'
            }

            articulate {
                sourceLanguage = 'en'
                ios {
                    catalog = file('ios/Shared.xcstrings')
                }
                $extraConfig
            }
            """.trimIndent(),
        )
    }

    /** A minimal, valid two-locale strings tree: `values/strings.xml` + `values-de/strings.xml`. */
    fun writeValidStringsFixture(projectDir: Path) {
        val stringsDir = File(projectDir.toFile(), "src/main/strings")
        File(stringsDir, "values").mkdirs()
        File(stringsDir, "values-de").mkdirs()
        File(stringsDir, "values/strings.xml").writeText(
            """
            <resources>
                <string name="hello">Hello</string>
                <string name="greeting">Hello, %1${'$'}s!</string>
            </resources>
            """.trimIndent(),
        )
        File(stringsDir, "values-de/strings.xml").writeText(
            """
            <resources>
                <string name="hello">Hallo</string>
                <string name="greeting">Hallo, %1${'$'}s!</string>
            </resources>
            """.trimIndent(),
        )
    }

    fun runner(projectDir: Path, vararg args: String): GradleRunner =
        GradleRunner.create()
            .withProjectDir(projectDir.toFile())
            .withPluginClasspath()
            .withArguments(*args)
            .forwardOutput()
}
