package net.sarazan.articulate.gradle

import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.Assumptions.assumeTrue
import java.io.File
import java.nio.file.Path

/**
 * Shared scaffolding for the plugin's TestKit functional tests (PLAN.md §4.8).
 *
 * Fixture build scripts are plain Groovy (`build.gradle`, `settings.gradle`),
 * not Kotlin DSL: `GradleRunner.withPluginClasspath()` injects the
 * plugin-under-test onto the fixture's buildscript classpath at runtime
 * (via `plugin-under-test-metadata.properties`, generated by
 * `plugin/build.gradle.kts`'s `gradlePlugin { testSourceSets(...) }`), and
 * assigning into a Gradle `Property<T>`/`RegularFileProperty` with plain `=`
 * only works through Groovy's built-in decoration for that -- Kotlin DSL
 * needs generated type-safe accessors that don't exist for a plugin applied
 * this way. Groovy is the standard fixture language for exactly this reason.
 */
internal object FunctionalTestSupport {

    /** Minimal settings file: just names the root project. No included builds -- the plugin classpath comes from TestKit injection, not `includeBuild`. */
    fun writeSettings(projectDir: Path, name: String = "fixture") {
        File(projectDir.toFile(), "settings.gradle").writeText(
            "rootProject.name = '$name'\n",
        )
    }

    /**
     * `build.gradle` applying `net.sarazan.articulate` and pointing the
     * committed catalog at `<projectDir>/ios/Shared.xcstrings`, matching the
     * DSL sketch in PLAN.md §E4.
     */
    fun writeBaseBuildFile(projectDir: Path, extraConfig: String = "") {
        File(projectDir.toFile(), "build.gradle").writeText(
            """
            plugins {
                id 'net.sarazan.articulate'
            }

            articulate {
                sourceLanguage = 'en'
                ios {
                    catalog = file('ios/Shared.xcstrings')
                }
                $extraConfig
            }
            """.trimIndent(),
        )
    }

    /** A minimal, valid two-locale strings tree: `values/strings.xml` + `values-de/strings.xml`. */
    fun writeValidStringsFixture(projectDir: Path) {
        val stringsDir = File(projectDir.toFile(), "src/main/strings")
        File(stringsDir, "values").mkdirs()
        File(stringsDir, "values-de").mkdirs()
        File(stringsDir, "values/strings.xml").writeText(
            """
            <resources>
                <string name="hello">Hello</string>
                <string name="greeting">Hello, %1${'$'}s!</string>
            </resources>
            """.trimIndent(),
        )
        File(stringsDir, "values-de/strings.xml").writeText(
            """
            <resources>
                <string name="hello">Hallo</string>
                <string name="greeting">Hallo, %1${'$'}s!</string>
            </resources>
            """.trimIndent(),
        )
    }

    fun runner(projectDir: Path, vararg args: String): GradleRunner =
        GradleRunner.create()
            .withProjectDir(projectDir.toFile())
            .withPluginClasspath()
            .withArguments(*args)
            .forwardOutput()

    /**
     * **Documentation only -- changing this changes nothing.** The AGP an
     * Android fixture actually gets is whatever `agpTestKitClasspath`
     * (`libs.versions.toml`'s `agp`) feeds into `pluginUnderTestMetadata`;
     * fixtures apply `com.android.application` with no version, deliberately
     * (see [writeAndroidAppModule]). This constant records the value that
     * mechanism is expected to supply.
     *
     * Verified 2026-07-31 by printing
     * `com.android.builder.model.Version.ANDROID_GRADLE_PLUGIN_VERSION` from a
     * live fixture: `8.5.2`, i.e. D9's floor at the time. REVISED 2026-08-03:
     * D9's floor moved to AGP 9.1.0 (PLAN.md §E2), which is what this
     * mechanism now supplies to every Android fixture -- both cells of the
     * matrix run this same AGP version, see [ANDROID_GRADLE_FLOOR_VERSION].
     * Re-verify by the same route, never by reading this constant.
     */
    const val AGP_VERSION = "9.1.0"

    /**
     * The Gradle floor for the **base** plugin (`net.sarazan.articulate`,
     * no AGP on its classpath, D10). [GradleFloorFunctionalTest] pins this
     * for the base plugin. AGP 8.5.x's own compatibility table historically
     * paired with the Gradle 8.7-8.9 range -- true when D9's floor was
     * 8.5.2 -- but that pairing no longer describes any Android fixture:
     * since the 2026-08-03 revision (PLAN.md §E2), Android fixtures pin
     * [ANDROID_GRADLE_FLOOR_VERSION] instead, not this constant.
     */
    const val GRADLE_FLOOR_VERSION = "8.7"

    /**
     * The Gradle floor for **Android** fixtures, which is now higher than the
     * base plugin's (D9, revised 2026-08-03 with the AGP 9.1 bump). AGP 9
     * requires Gradle >= 9.1.0, but `net.sarazan.articulate` itself has no AGP
     * on its classpath at all (D10) and still works on [GRADLE_FLOOR_VERSION].
     *
     * Kept as a **separate** constant rather than raising the shared one: a
     * single floor would have silently claimed every non-Android consumer needs
     * Gradle 9.1 to use the base plugin, narrowing the supported range with
     * nothing failing to reveal it. [GradleFloorFunctionalTest] still proves the
     * base plugin at 8.7; only Android fixtures pin this.
     */
    const val ANDROID_GRADLE_FLOOR_VERSION = "9.3.1"

    /**
     * `compileSdk`/`targetSdk` for Android fixtures. 37 because AGP 9.1 is
     * the floor now, only SDK 34/37 are installed, and -- since the
     * 2026-08-03 revision put both matrix cells on the same AGP version --
     * this one constant now serves both [AndroidWiringFunctionalTest] and
     * [AndroidWiringGradleCurrentFunctionalTest]; there is no longer a
     * separate AGP-9.1-cell constant.
     */
    const val COMPILE_SDK = 37

    /**
     * Locates a real Android SDK the way a developer's machine actually has
     * one -- `ANDROID_HOME`, then `ANDROID_SDK_ROOT`, then this machine's
     * default install path -- and never relies on the ambient shell
     * environment alone: `ANDROID_HOME` is not set in non-interactive shells
     * here (a `.zshrc` export doesn't reach them), and even where it is set,
     * TestKit runs each fixture as a nested build in a fresh temp directory
     * with no `local.properties` of its own (see [writeLocalProperties]).
     * Returns `null` if none of the three candidates look like a real SDK
     * (checked via the `platforms/` directory, not mere existence).
     */
    fun findAndroidSdk(): File? {
        val candidates = listOfNotNull(
            System.getenv("ANDROID_HOME"),
            System.getenv("ANDROID_SDK_ROOT"),
            "${System.getProperty("user.home")}/Library/Android/sdk",
        )
        return candidates.map(::File).firstOrNull { it.isDirectory && File(it, "platforms").isDirectory }
    }

    /**
     * The strictness switch (PLAN.md §13 infra gap). On a fresh CI runner
     * with no SDK, [findAndroidSdk] returning `null` used to be indistinguishable
     * from "developer machine with no SDK installed" -- both silently skipped
     * via `Assumptions.assumeTrue`, so a CI run that never had an SDK in the
     * first place still went green while testing none of [AndroidWiringFunctionalTest].
     * That is exactly the "invisible corpus" failure mode this project has
     * repeatedly found (assertions/skips satisfied by their own absence).
     *
     * Set to `"true"` (case-insensitive), a missing SDK becomes a hard failure
     * instead of a skip -- CI sets this always (see the workflow). Left unset,
     * local runs keep skipping, so a contributor without an SDK installed
     * isn't blocked. See [resolveRequiredAndroidSdk] for the actual branching
     * logic, kept separate and pure so it's unit-testable without needing to
     * fake environment variables or a real filesystem.
     */
    const val REQUIRE_ANDROID_SDK_ENV = "ARTICULATE_REQUIRE_ANDROID_SDK"

    /**
     * Pure decision logic for [REQUIRE_ANDROID_SDK_ENV], factored out of
     * [requireOrSkipAndroidSdk] specifically so it can be unit-tested (see
     * `FunctionalTestSupportTest`) without touching real environment
     * variables or the filesystem -- both [sdk] and [requireEnvValue] are
     * plain parameters here, not read from `System` directly.
     *
     *  - [sdk] non-null: returned as-is; the env var is irrelevant when an
     *    SDK was actually found.
     *  - [sdk] null and [requireEnvValue] is `"true"` (case-insensitive):
     *    throws [IllegalStateException] naming [REQUIRE_ANDROID_SDK_ENV] and
     *    the locations checked -- a hard failure, never a silent skip.
     *  - [sdk] null and anything else (including unset): aborts the current
     *    test via `Assumptions.assumeTrue`, i.e. a clean, loud skip -- never
     *    silent, since the message names exactly what was checked and how to
     *    make it strict instead.
     */
    fun resolveRequiredAndroidSdk(sdk: File?, requireEnvValue: String?): File {
        if (sdk != null) return sdk
        val checked = "ANDROID_HOME, ANDROID_SDK_ROOT, and ~/Library/Android/sdk"
        if (requireEnvValue?.equals("true", ignoreCase = true) == true) {
            throw IllegalStateException(
                "No Android SDK found (checked $checked). $REQUIRE_ANDROID_SDK_ENV=true requires one to " +
                    "be present -- install an SDK with platforms + build-tools and point ANDROID_HOME or " +
                    "ANDROID_SDK_ROOT at it.",
            )
        }
        assumeTrue(
            false,
            "No Android SDK found (checked $checked) -- skipping. Set $REQUIRE_ANDROID_SDK_ENV=true to " +
                "make this a hard failure instead of a skip (CI always does).",
        )
        error("unreachable: Assumptions.assumeTrue(false, ...) always throws")
    }

    /**
     * [findAndroidSdk] plus [resolveRequiredAndroidSdk]'s strictness switch,
     * reading the real environment. The one entry point functional tests
     * should call from `@BeforeEach`.
     */
    fun requireOrSkipAndroidSdk(): File =
        resolveRequiredAndroidSdk(findAndroidSdk(), System.getenv(REQUIRE_ANDROID_SDK_ENV))

    /**
     * Writes `local.properties` into a TestKit fixture pointing at [sdkDir].
     * Required because each TestKit run is a fresh temp project AGP cannot
     * configure without knowing where the SDK is, and this project
     * deliberately does not depend on ambient `ANDROID_HOME` reaching the
     * nested build (it doesn't, reliably) -- see [findAndroidSdk]. Backslash
     * escaping matters for a `.properties` file even though every SDK path
     * used in practice here is POSIX.
     */
    fun writeLocalProperties(projectDir: Path, sdkDir: File) {
        File(projectDir.toFile(), "local.properties").writeText(
            "sdk.dir=${sdkDir.absolutePath.replace("\\", "\\\\")}\n",
        )
    }

    /**
     * Multi-module settings file for the Android fixtures: `:i18n` (the
     * strings source module, `net.sarazan.articulate`) and `:app` (the
     * Android app module, `net.sarazan.articulate.android` + `com.android.application`).
     * [modules] is only the `include` order; it is **not** the evaluation
     * order. Gradle configures siblings in alphabetical path order, so `:app`
     * is always evaluated before `:i18n` here, and `:i18n`'s
     * `generateAndroidRes` therefore does *not* exist yet when AGP fires
     * `:app`'s `onVariants` callbacks. [ArticulateAndroidPlugin]'s
     * `evaluationDependsOn` is what makes the lookup work anyway --
     * mutation-verified, see `AndroidWiringFunctionalTest.writeTwoModuleFixture`.
     * (A previous revision of this doc claimed the opposite, that listing
     * `:i18n` first made it evaluate first. It does not. Corrected 2026-07-31.)
     * `google()` is required in `dependencyResolutionManagement`
     * even though AGP's own jar reaches the fixture via the injected
     * plugin-under-test classpath, not via these repositories (see
     * [writeAndroidAppModule]) -- AGP dynamically resolves its own runtime
     * dependencies (aapt2's native binary, in particular) as ordinary Maven
     * coordinates against *this* project's repositories once applied, and
     * those are only published to Google's Maven repo. `pluginManagement`
     * carries `google()` too, mirroring the real repo's root
     * `settings.gradle.kts`, even though nothing here currently resolves a
     * plugin marker through it.
     */
    fun writeAndroidSettings(projectDir: Path, name: String = "fixture", modules: List<String> = listOf("i18n", "app")) {
        File(projectDir.toFile(), "settings.gradle").writeText(
            """
            pluginManagement {
                repositories {
                    google()
                    gradlePluginPortal()
                    mavenCentral()
                }
            }
            dependencyResolutionManagement {
                repositories {
                    google()
                    mavenCentral()
                }
            }
            rootProject.name = '$name'
            ${modules.joinToString("\n            ") { "include ':$it'" }}
            """.trimIndent(),
        )
    }

    /**
     * The Android app module: applies `net.sarazan.articulate.android` and
     * `com.android.application` (pinned to [AGP_VERSION] via `plugin`'s own
     * `testImplementation(libs.android.gradle.plugin)`, see `plugin/build.gradle.kts`),
     * with `articulateAndroid { i18nProject = ... }` pointing back at the
     * sibling i18n module.
     *
     * AGP is applied with the **legacy** `apply plugin: 'com.android.application'`
     * rather than `plugins { id 'com.android.application' version '...' }`
     * deliberately: [ArticulateAndroidPlugin] references AGP's
     * `ApplicationAndroidComponentsExtension` API, and that reference only
     * resolves at runtime here if AGP's classes live in the *same* classloader
     * TestKit's `withPluginClasspath()` injects our plugin's own classes
     * into. Requesting `com.android.application` through the versioned
     * `plugins {}` DSL resolves it independently (from `google()`), loading a
     * second, distinct copy of AGP's classes in a different classloader --
     * empirically this throws `NoClassDefFoundError` for
     * `ApplicationAndroidComponentsExtension` even though the class is
     * present under both names. The legacy `apply plugin:` form instead
     * looks up an already-loaded implementation on the existing classpath,
     * which is exactly the one `testImplementation` put there.
     *
     * Also drops a `Marker.java` referencing `R.string.hello` -- compiling it
     * is the strongest available proof that the generated Android res
     * actually reached AGP's resource merge and R-class generation, not
     * merely that some task ran (see [AndroidWiringFunctionalTest]).
     */
    fun writeAndroidAppModule(
        projectDir: Path,
        moduleName: String = "app",
        i18nProjectPath: String = ":i18n",
        compileSdk: Int = COMPILE_SDK,
        withMarker: Boolean = true,
    ) {
        val appDir = File(projectDir.toFile(), moduleName).apply { mkdirs() }
        File(appDir, "build.gradle").writeText(
            """
            plugins {
                id 'net.sarazan.articulate.android'
            }

            apply plugin: 'com.android.application'

            android {
                namespace 'net.sarazan.articulate.fixture.app'
                compileSdk $compileSdk

                defaultConfig {
                    applicationId 'net.sarazan.articulate.fixture.app'
                    minSdk 24
                    targetSdk $compileSdk
                }
            }

            articulateAndroid {
                i18nProject = '$i18nProjectPath'
            }
            """.trimIndent(),
        )
        val mainDir = File(appDir, "src/main").apply { mkdirs() }
        File(mainDir, "AndroidManifest.xml").writeText(
            """
            <manifest xmlns:android="http://schemas.android.com/apk/res/android">
                <application />
            </manifest>
            """.trimIndent(),
        )
        if (withMarker) {
            val javaDir = File(mainDir, "java/net/sarazan/articulate/fixture/app").apply { mkdirs() }
            File(javaDir, "Marker.java").writeText(
                """
                package net.sarazan.articulate.fixture.app;

                /** Compiles only if R.string.hello resolves -- proof the generated Android res reached AGP's merge (PLAN.md §4.5). */
                public final class Marker {
                    public static final int HELLO_STRING_ID = R.string.hello;
                    private Marker() {}
                }
                """.trimIndent(),
            )
        }
    }
}
